Make option parsing code more maintainable.

diff --git a/bin/arttime b/bin/arttime
--- a/bin/arttime
+++ b/bin/arttime
@@ -30,53 +30,37 @@ zmodload zsh/terminfo
 #     -tf-other:=tfother_arg \
 
 if is-at-least "5.8"; then
-    zparseopts -D -E -F - \
-        a:=artname_arg \
-        b:=flipartname_arg \
-        -random=random_arg \
-        t:=title_arg \
-        g:=goal_arg \
-        h=help_arg \
-        -theme:=theme_arg \
-        -tc:=titlecolor_arg \
-        -ac:=artcolor_arg \
-        -style:=style_arg \
-        -pa:=pbpendingchar_arg \
-        -pb:=pbcompletechar_arg \
-        -pl:=pblength_arg \
-        -hours:=hours_arg \
-        -debug=debug_arg \
-        -nolearn=nolearn_arg \
-        -version=version_arg \
-        -help=help_arg \
-        || return
+    zparseoptscmd='zparseopts -D -E -F - '
 else
-    zparseopts -D -E - \
-        a:=artname_arg \
-        b:=flipartname_arg \
-        -random=random_arg \
-        t:=title_arg \
-        g:=goal_arg \
-        h=help_arg \
-        -theme:=theme_arg \
-        -tc:=titlecolor_arg \
-        -ac:=artcolor_arg \
-        -style:=style_arg \
-        -pa:=pbpendingchar_arg \
-        -pb:=pbcompletechar_arg \
-        -pl:=pblength_arg \
-        -hours:=hours_arg \
-        -debug=debug_arg \
-        -nolearn=nolearn_arg \
-        -version=version_arg \
-        -help=help_arg \
-        || return
-    if [[ "${#@}" != "0" ]]; then
-        printf "Error: arttime does not understand the following part of passed options,\n    "
-        printf ' %s ' "[1m[4m$@[0m"
-        printf '\n%s\n' "check the valid options by invoking arttime with --help"
-        exit 1
-    fi
+    zparseoptscmd='zparseopts -D -E - '
+fi
+
+$(printf "$zparseoptscmd") \
+   a:=artname_arg \
+   b:=flipartname_arg \
+   -random=random_arg \
+   t:=title_arg \
+   g:=goal_arg \
+   h=help_arg \
+   -theme:=theme_arg \
+   -tc:=titlecolor_arg \
+   -ac:=artcolor_arg \
+   -style:=style_arg \
+   -pa:=pbpendingchar_arg \
+   -pb:=pbcompletechar_arg \
+   -pl:=pblength_arg \
+   -hours:=hours_arg \
+   -debug=debug_arg \
+   -nolearn=nolearn_arg \
+   -version=version_arg \
+   -help=help_arg \
+   || return
+
+if [[ "${#@}" != "0" ]]; then
+    printf "Error: arttime does not understand the following part of passed options,\n    "
+    printf ' %s ' "[1m[4m$@[0m"
+    printf '\n%s\n' "check the valid options by invoking arttime with --help"
+    exit 1
 fi
 
 function printhelp {
